data_dir: 'data/'
cur_dataset_dir: 'data/UPB-DE/'

vocab_dir: 'data/vocab/de'
token_vocab_file: 'token_vocab.txt'
char_vocab_file: 'char_vocab.txt'
prd_type_vocab_file: 'prd_type_vocab.txt'
role_type_vocab_file: 'role_type_vocab.txt'
action_vocab_file: 'action_vocab.txt'
pos_vocab_file: 'pos_vocab.txt'
dep_type_vocab_file: 'dep_type_vocab.txt'

write_eval_file_dev: 'data/UPB-DE/eval_file_dev.txt'
write_eval_file_test: 'data/UPB-DE/eval_file_test.txt'

pickle_dir: 'data/pickle/de'
vec_npy: 'data/pickle/de/word_vec.npy'
inst_pl_file: 'data/pickle/de/data.pl'
model_save_file: 'data/pickle/de/model.ckpt'


#train_sent_file: 'data/bert_emb/train_bert.npy'
#dev_sent_file: 'data/bert_emb/dev_bert.npy'
#test_sent_file: 'data/bert_emb/test_bert.npy'


embedding_dir: 'G:\datasets\embeddings\de\'
embedding_file: 'cc.de.300.vec'
embedding_type: 'fasttext'


normalize_digits: false
lower_case: false